### ISSUE TITLE
User can save a note.

### ISSUE THREAD

**Issue by gdegas** [gdegas/Web-api#1]

**Comment by gdegas** [comment]
# Motivation
User can have note saved for later

# Tasks
- [x] create an index.js
- [x] install express through npm as a dependency
- [x] install nodemon as a dev dependency
- [x] add scripts to the 'package.json' for run and watch.
- [x] require the express package and set it to variable
- [x] install and set require body-parser to a const variable
- [x] create an app object for express
- [x] create an empty array
- [x] set app.use to parse body into JSON with body-parser
- [x] create a Get method on the express app that respond with JSON of the body
- [x] create a POST method on the express app to write req body into the array of notes.
- [x] respond with sendStatus method of 201
- [x] create listen method on the express app to listen on port 3000
